### ISSUE TITLE
SoCal Approach Combined shows the wrong airspace. Shows LAX_DEP airspace.

### ISSUE THREAD

**Issue by VeIocityy** [daniluk4000/vatsim-radar#243] opened 2024-08-05 03:34 UTC
### Your Vatsim CID

1573809

### Radar version

0.4.3

### Describe your issue

The SCT_APP airspace shows as the LAX_EDP airspace. 
![VATSIM-Radar map](https://github.com/user-attachments/assets/4031dcc1-cae1-4d6e-a220-002f32ab4f78)
Should be this instead https://github.com/vatsimnetwork/simaware-tracon-project/blob/main/Boundaries/SCT/SCT.json not this https://github.com/vatsimnetwork/simaware-tracon-project/blob/main/Boundaries/SCT/LAX_DEP.json.

### Reproduction steps

Sign onto the VATSIM-Radar website when SCT_APP is online.

### Platform

Windows, chrome. 127.0.6533.89 (Official Build) (64-bit) (cohort: Stable) 

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment] 2024-08-05 09:03
Duplicate of https://github.com/daniluk4000/vatsim-radar/issues/216

Will be fixed in 0.4.4

**Closed by daniluk4000** 2024-08-05 09:03 UTC
Labels: bug, pending triage
