### ISSUE TITLE
Departure and Arrival Rate History

### ISSUE THREAD

**Issue by fdrake97** [daniluk4000/vatsim-radar#160] opened 2024-07-10 21:08 UTC
### Your Vatsim CID

1664386

### What do you suggest?

Display a rolling average departure and arrival rate for a particular airport, over the past 30 mins, 1 hour, or similar. For example: "Average Time between Departures(/Arrivals): 3.25 min".

### Why do you need that?

This would help people get an idea of traffic, especially at busy event times. A pilot could use this information to get an idea of how long it might be before departure if they are in a long queue of departures, or holding in a long string of arrivals. Controllers could potentially benefit as well. On the ground, it could help ATC get an idea of how quickly traffic is flowing out of the airport, and for arrivals it could help controllers know in advance how much holding or delays there might be, if they know the rate of scheduled arrivals vs. the rate planes are actually landing.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment] 2024-07-27 15:41
Basically duplicate of https://github.com/daniluk4000/vatsim-radar/issues/160

**Closed by daniluk4000** 2024-07-27 15:41 UTC
Labels: enhancement, considering
