### ISSUE TITLE
Remove aircraft on the ground

### ISSUE THREAD

**Issue by P-Sergienko** [daniluk4000/vatsim-radar#261] opened 2024-08-13 12:46 UTC
### Your Vatsim CID

1489535

### What do you suggest?

I'd like not to see aircraft on the ground at low zoom levels.

### Why do you need that?

When all the aircraft are displayed on the ground, it looks like a mess. You can't deal with what's going on at an airport; moreover, it's tricky to hit an airport label or aircraft icons. What I suggest is to remove the display of airplanes at airports, so there will be less useless information.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by DotWallop** [comment] 2024-08-14 21:29
Duplicate of #132

**Closed** 2024-08-14 21:31 UTC
Labels: duplicate, enhancement
