### ISSUE TITLE
Add airport names in the hover menu 

### ISSUE THREAD

**Issue by redrails** [daniluk4000/vatsim-radar#280] opened 2024-08-19 13:54 UTC
### Your Vatsim CID

1820346

### What do you suggest?

When hovering over a live flight, the "From" and "To" aerodromes are in ICAO format. 

![image](https://github.com/user-attachments/assets/f53592ff-e8e4-4299-97a8-a222cea09f95)

It would be great to have the actual airport names just underneath. Currently the best way I can find to access this information is by clicking on the flight. 

### Why do you need that?

It would make it easier to see at a glance where a flight is headed, and especially useful if you are tracking a flight on the same path as yours. 

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment] 2024-08-19 13:57
Duplicate of https://github.com/daniluk4000/vatsim-radar/issues/194

(will be done in 0.4.4)

**Closed by daniluk4000** 2024-08-19 13:57 UTC
Labels: enhancement, pending triage
