### ISSUE TITLE
Track Aircraft near 180E/W - Screen bounces around

### ISSUE THREAD

**Issue by m-9c** [daniluk4000/vatsim-radar#175] opened 2024-07-15 05:14 UTC
### Your Vatsim CID

974571

### Radar version

0.4.2

### Describe your issue

The track aircraft button centres an aircraft on the screen.

When an aircraft is near 180 longitude, and the user is zoomed out far enough, the aircraft cannot be centered. The window then keeps "bouncing" across to try and cross the longitude boundary.

I'd expect either the panning stops at the maximum longitude, or zooms in to allow the aircraft to be centered.

https://github.com/user-attachments/assets/d27fb1c0-bedd-4e75-9f9d-6421016fee50

### Reproduction steps

See attached video:

- Have aircraft flying close to longitude 180.
- Pan away from the aircraft
- Press the "Track aircraft" icon

### Platform

Chrome, Windows

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by daniluk4000** [comment] 2024-07-27 15:48
Duplicate of https://github.com/daniluk4000/vatsim-radar/issues/157

**Closed by daniluk4000** 2024-07-27 15:48 UTC
Labels: bug, confirmed
